### PR TITLE
Assets path defer js

### PR DESCRIPTION
**Pull request by jpdevries**
Adding support for Sub Folder Contexts, Making Reset-able Configurable

### CODE REVIEW

**Comment by jpdevries** [comment]
looking at the details, but not sure why Travis CI failed

**Comment by jpdevries** [comment]
I forgot to mention, there also is a scriptsBottom option that loads the scripts at the bottom of the page rather than in  the header. This is particularly useful when using disabling `loadjQuery` because you are using something like HTML5 Boilerplate and loading the jQuery at the bottom of the page.

**Comment by goldsky** [comment]
are you tying to create a different connector to serve different processors?

**Comment by goldsky** [comment]
I have my own reason why I put JS libraries at the head section, not at the bottom.
Some times I put inline function inside the HTML body.
eg:

``` html
<a href="#" onclick="countThis($(this).parent());">rate</a>
```

I put the rest of the custom JS files at the bottom.

**Comment by jpdevries** [comment]
No but as is it doesn't support contexts with different asset_url and base_href than web context because assets/ is hardcoded. 

—

**Pull request merged**
